apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  labels:
    service: demo
    foo: bar
spec:
  containers:
  - name: api
    image: nginx
    resources:
      requests:
        cpu: 500m
  - name: frontend
    image: nginx
    resources:
      requests:
        cpu: 250m
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    service: db
    bar: foo
spec:
  containers:
  - name: db
    image: nginx
    resources:
      requests:
        cpu: 1
